### ISSUE TITLE
bankroll not updating appropriately 

### ISSUE THREAD

**Issue by johnahartv** [Marconiusiii/OhCraps#1]
There is the  response with comment  in ():
Last login: Mon Nov 15 08:18:19 on ttys001

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
snkxm-jhart2:~ jhart$ /Users/jhart/Downloads/OhCraps-master-2/OhCraps_Py3.command ; exit;
Oh Craps! v.6.0.3
By: Marco Salsiccia
How much are you cashing in for your bankroll?
$>1000 **(starting Bankroll)**
Great, starting you off with $1000.
You have $1000 in the bank.
Rolls: 0

Place your Bets!

> r
Rolling the dice!
7 winner! Pay the line, take the don't!
You have $1000 in the bank.
Rolls: 0

Place your Bets!

> r
Rolling the dice!
5, a 4 1 5!
You have $1000 in the bank.
5 is the Point!
Rolls: 1
Place your bets!

> p
Place Bets?
>y
You have $0 on the Place 4.
How much on the Place 4?
$>
You have $0 on the Place 5.
How much on the Place 5?
$>100
$100 on the Place 5.
You have $0 on the Place 6.
How much on the Place 6?
$>120
$120 on the Place 6.
You have $0 on the Place 8.
How much on the Place 8?
$>120
$120 on the Place 8.
You have $0 on the Place 9.
How much on the Place 9?
$>0
You have $0 on the Place 10.
How much on the Place 10?
$>0
You have $100 on the Place 5.
You have $120 on the Place 6.
You have $120 on the Place 8.
Place Bets?
>x
Done Place Betting!
Place your bets!

> f
Field Bet?

>y
How much on the Field?
	$> 70
Ok, $70 on the Field.
Place your bets!

> r
Dice are rolling!
4, Hit us in the 2 2!
You won $70 on the Field!
Change your Field bet?
>y
How much on the Field?
	$> 0
Taking down your Field bet.
You have $660 in the bank with $340 out on the table. **(this should be $730 in the bank with $340 on the table) **
5 is the Point!
Rolls: 2
Place your bets!

> 

I've tried this several times with different bankroll amounts and it always the same.. Additionally I'll then pull down to 66 inside.  In theory if I seven out I could still have 1004 in my bankroll but i take the 66 out of a 1000.  hope that makes sense

**Comment by Marconiusiii** [comment]
Sorry for missing this issue! I've since fixed how the bank functions when taking down bets with the Field and other options. Was accidentally not returning the amount to the bank in the take down functions, but was updating the chipsOnTable variable. Try the latest version, and sorry for all the lost chips! :)
